### ISSUE TITLE
MVP's

### ISSUE THREAD

**Issue by simcha-c** [davidyoon85/CampAway#1]
Hey David, 

Your MVP's are looking great! Here are a few things to add/change in the list. 

User Login MVP: 
- [ ] a user shouldn't be able to book spots when not logged in (as you've said), but also shouldnt be able to create a booking if not logged in.

Spots MVP:
- [ ] spots need to come before bookings. Since you need a spot in order to book it, that should be done first.
- [ ] users should also be able to create spots
- [ ] be able to edit spots and delete spots
- [ ] reviews come after spots, so take out reviews from spots.
- [ ] does a spot also entail a spot show page?
- [ ] spots will probably take two days to complete.

Bookings MVP:
- [ ] messages will come later. That should be one of your bonus features.
- [ ] I think a user adding a photo is part of reviews. So that will be part of the reviews mvp.
- [ ] what does booking a spot entail? usually dates. seeing if the dates are available to the spot.
- [ ] the spot owner needs to approve the booking?

Spot Search MVP:
- [ ] search can include group size and price, but doesn't have to search by amenities, activities, etc. That's a cool bonus feature, but it doesnt need to be right now.
- [ ] search should include the map on the page though. With all the locations on the map.

Reviews MVP:
- [ ] What does a review entail? a review can be if they recommend the spot. 
- [ ] Users can leave a body for the review.
- [ ] only if they camped at the spot (which you said)
- [ ] with a review, you can add a photo.

**Comment by davidyoon85** [comment]
Hi Simcha,

Thank you for your feedback. I believe i've corrected the issues.
